/*
* Morgan Williams-Burrell
* CSC 350
* Notes: 
*      -This is the header file for hw3
*      -This file contains the color struct, defined colors, 
*       and the color map for the image
*/

// Store the RGB values for the color
const typedef struct COLOR {
  GLfloat r;
  GLfloat g;
  GLfloat b;
} Color;

/*List of Colors*/
Color BK = {0.00f , 0.00f, 0.00f}; //Black
Color WH = {1.00f , 1.00f, 1.00f}; //White
Color VD = {1.00f , 0.50f, 0.30f}; //The color for the background

Color LG = {0.32f , 0.67f, 0.55f}; //Light Green
Color BG = {0.06f , 0.51f, 0.41f}; //Base Green
Color DG = {0.31f , 0.37f, 0.34f}; //Dark Green
Color MG = {0.06f , 0.18f, 0.16f}; //Moss Green

Color LR = {1.00f , 0.58f, 0.58f}; //Light Red / Pink
Color BR = {0.94f , 0.24f, 0.35f}; //Base Red
Color DR = {0.70f , 0.18f, 0.25f}; //Dark Red
Color MR = {0.39f , 0.24f, 0.25f}; //Mouth Red
Color DP = {0.78f , 0.46f, 0.49f}; //Dark Pink

Color LB = {0.61f , 0.84f, 1.00f}; //Light Blue
Color BB = {0.41f , 0.62f, 0.77f}; //Base Blue
Color SB = {0.40f , 0.56f, 0.67f}; //Slate Blue
Color DB = {0.18f , 0.34f, 0.44f}; //Dark Blue
Color WB = {0.85f , 0.93f, 0.99f}; //White Blue

Color LY = {0.71f , 0.75f, 0.76f}; //Light Grey
Color BY = {0.32f , 0.33f, 0.32f}; //Base Grey
Color DY = {0.25f , 0.25f, 0.28f}; //Dark Grey


//An array that holds the what color each pixel will be
const Color imageArray[] = 
{
//      01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
/*1*/   VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,BK,BK,BK,BK,BK,BK,BK,BK,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,
/*2*/   VD,VD,VD,VD,VD,VD,VD,VD,BK,BK,BK,LR,LR,BR,DR,LB,LB,LB,LB,LB,BK,BK,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,
/*3*/   VD,VD,VD,VD,VD,VD,BK,BK,LR,LR,LR,MR,BR,BR,DR,DR,LB,LB,LB,SB,SB,SB,BK,VD,VD,VD,VD,VD,VD,VD,VD,VD,
/*4*/   VD,VD,VD,VD,BK,BK,DB,DB,DP,DP,BR,BR,BR,BR,DR,DR,LB,SB,SB,LB,LB,LB,BK,VD,VD,VD,VD,VD,VD,VD,VD,VD,
/*5*/   VD,VD,VD,BK,WH,WH,WB,WB,DB,DB,BR,BR,BR,BR,DR,LB,LB,LB,LB,LB,SB,BK,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,
/*6*/   VD,VD,BK,WH,WH,WB,WB,WB,WB,WB,DB,DB,BR,DR,LB,LB,LB,SB,SB,SB,BK,BK,BK,VD,VD,VD,VD,VD,VD,VD,VD,VD,
/*7*/   VD,BK,WH,WH,WB,WB,WB,WB,WB,WB,LR,DB,BR,DR,LB,LB,SB,LB,LB,SB,MR,DR,BG,BK,BK,VD,VD,VD,VD,VD,VD,VD,
/*8*/   VD,BK,DB,DB,DB,WB,WB,DY,BY,BY,WB,DB,DR,LB,LB,LB,LB,LB,BB,DY,DR,DY,DR,BG,MG,MG,VD,VD,VD,VD,VD,VD,
/*9*/   BK,WB,WB,WB,LB,DB,DY,WH,BK,WH,DB,LY,LB,LB,LB,LB,LB,BB,DY,DY,DR,DR,DG,DG,DR,MG,BK,VD,VD,VD,VD,VD,
/*10*/  BK,WH,WB,LB,LB,LB,DY,WH,BK,WH,BY,LB,LB,LB,LB,LB,LB,SB,DY,DP,DG,DG,DP,DP,DG,DR,BK,BK,VD,VD,VD,VD,
/*11*/  BK,WH,LB,LB,LB,LB,LY,DY,BY,BY,LB,LB,LB,LB,LB,LB,SB,BK,BK,BK,DG,DP,DP,DG,DG,DG,DR,BK,VD,VD,VD,VD,
/*12*/  BK,LB,SB,LB,LB,LB,LB,LB,LB,SB,LB,LB,LB,LB,LB,SB,BK,VD,VD,VD,BK,BY,DY,DR,DR,DR,BG,BR,BK,VD,VD,VD,
/*13*/  VD,BK,LB,SB,LB,LB,DY,LB,SB,LB,WH,LB,LB,LB,BB,BK,VD,VD,VD,VD,BK,LR,LR,BG,BG,DR,BG,BR,BK,VD,VD,VD,
/*14*/  VD,VD,BK,BK,LB,MR,DR,DY,DY,LB,LB,LB,LB,BB,DY,BB,BK,VD,BK,BK,DR,DG,LR,LR,LR,DG,BR,BG,BG,BK,VD,VD,
/*15*/  VD,VD,VD,BK,MR,MR,DR,DR,DY,LB,LB,LB,BB,DY,BB,LB,LB,BK,MR,LR,DG,DR,DG,LR,LR,DG,BR,BG,BG,BK,VD,VD,
/*16*/  VD,VD,VD,BK,BB,DY,MR,MR,MR,MR,BB,BB,DY,SB,LB,LB,DY,DY,DG,LR,LR,DG,BR,DG,DG,BR,BR,BG,BG,BK,VD,VD,
/*17*/  VD,VD,BK,LY,DY,BB,MR,BB,MR,BB,BK,BK,BK,LB,LB,DY,WH,DY,LR,DY,LR,LR,DG,DG,BR,BG,BG,BR,BG,BK,VD,VD,
/*18*/  VD,VD,BK,LY,DY,DY,BB,BB,BB,BK,VD,BK,WH,BY,BY,LY,WH,WH,DY,DY,LR,DG,BR,BR,BG,BG,BG,BG,LG,LG,BK,VD,
/*19*/  VD,VD,BK,LY,LY,LY,BK,BK,BK,VD,VD,BK,LY,WH,LY,WH,SB,WH,DY,BG,DY,DR,BR,BG,BG,BG,BG,LG,LG,LG,BK,VD,
/*20*/  VD,VD,VD,BK,LY,BK,VD,VD,VD,VD,VD,BK,LY,WH,SB,WH,LY,WH,BR,BG,BG,DY,DG,BR,DG,DG,DG,LG,LG,BK,VD,VD,
/*21*/  VD,VD,VD,VD,BK,VD,VD,VD,VD,VD,BK,DG,DY,WH,SB,WH,DY,DY,BR,BR,BG,DY,DG,DG,BG,BG,BG,DG,LG,BK,VD,VD,
/*22*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,DR,DY,DY,LY,WH,DY,BG,BR,BR,BG,DY,BR,BR,BR,BR,BG,BG,BK,VD,VD,VD,
/*23*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,DR,DR,DY,DY,DY,BG,BG,LR,BG,DY,BG,BG,BG,BG,BR,BR,BG,BK,VD,VD,VD,
/*24*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,DG,DR,DY,BG,BR,BR,BR,BR,DY,BG,BR,BR,BR,BG,BG,BG,BG,BK,VD,VD,VD,
/*25*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,DG,DG,DY,BG,BG,BG,BG,DY,BR,BR,BR,BR,BR,BG,BG,BK,VD,VD,VD,VD,
/*26*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,MG,MG,BG,DY,DY,BR,BR,BR,DG,BG,BG,BG,BR,BR,BG,BK,VD,VD,VD,VD,
/*27*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,DP,DY,DY,DG,DG,DY,BK,BK,BK,BK,BG,BG,BG,BG,DG,BK,VD,VD,VD,VD,
/*28*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,DP,MR,DP,DP,MR,DG,BK,VD,VD,VD,VD,BK,DY,DG,DG,DG,BK,VD,VD,VD,VD,  
/*29*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,BK,BK,BK,BK,BK,VD,VD,VD,VD,BK,BR,DY,DR,DG,DG,BK,VD,VD,VD,VD,
/*30*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,LR,LR,DY,LR,DY,LR,BK,VD,VD,VD,VD,
/*31*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,BK,BK,LR,LR,DR,LR,BK,VD,VD,VD,VD,
/*32*/  VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,VD,BK,BK,BK,BK,VD,VD,VD,VD,VD,
};